# Generated by Django 5.2.11 on 2026-02-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=50, unique=True),
        ),
    ]
